### ISSUE TITLE
NameError Bibsonomy::API with version 0.4.14

### ISSUE THREAD

**Issue by ptoews** [rjoberon/bibsonomy-ruby#3]
Something seems broken with the newest version. When I try to run jekyll with bibsonomy-jekyll I get the following error message caused by this gem:

```
$ jekyll build --trace
            Source: .
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: uninitialized constant BibSonomy::API in /_layouts/person.html
Traceback (most recent call last):
	43: from /home/philipp/gems/bin/jekyll:23:in `<main>'
	42: from /home/philipp/gems/bin/jekyll:23:in `load'
	41: from /home/philipp/gems/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
	40: from /home/philipp/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	39: from /home/philipp/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	38: from /home/philipp/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	37: from /home/philipp/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	36: from /home/philipp/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	35: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	34: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:36:in `process'
	33: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:65:in `build'
	32: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/command.rb:28:in `process_site'
	31: from /home/philipp/gems/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:44:in `process'
	30: from /home/philipp/gems/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:44:in `each'
	29: from /home/philipp/gems/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:45:in `block in process'
	28: from /home/philipp/gems/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:69:in `process_language'
	27: from /home/philipp/gems/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:76:in `process_default_language'
	26: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:71:in `process'
	25: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:191:in `render'
	24: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `render_docs'
	23: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `each_value'
	22: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `block in render_docs'
	21: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `each'
	20: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	19: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/site.rb:479:in `render_regenerated'
	18: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:62:in `run'
	17: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:88:in `render_document'
	16: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	15: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:195:in `render_layout'
	14: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:126:in `render_liquid'
	13: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	12: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	11: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	10: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	 9: from /home/philipp/gems/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	 8: from /home/philipp/gems/gems/liquid-4.0.1/lib/liquid/template.rb:220:in `render!'
	 7: from /home/philipp/gems/gems/liquid-4.0.1/lib/liquid/template.rb:207:in `render'
	 6: from /home/philipp/gems/gems/liquid-4.0.1/lib/liquid/template.rb:242:in `with_profiling'
	 5: from /home/philipp/gems/gems/liquid-4.0.1/lib/liquid/template.rb:208:in `block in render'
	 4: from /home/philipp/gems/gems/liquid-4.0.1/lib/liquid/block_body.rb:91:in `render'
	 3: from /home/philipp/gems/gems/liquid-4.0.1/lib/liquid/block_body.rb:102:in `render_node_to_output'
	 2: from /home/philipp/gems/gems/bibsonomy-jekyll-0.1.7/lib/bibsonomy-jekyll.rb:50:in `render'
	 1: from /home/philipp/gems/gems/bibsonomy-jekyll-0.1.7/lib/bibsonomy-jekyll.rb:50:in `new'
/home/philipp/gems/gems/bibsonomy-0.4.14/lib/bibsonomy/csl.rb:93:in `initialize': uninitialized constant BibSonomy::API (NameError)
```

When I downgrade to 0.4.13 the error is gone immediately. I've also tried to reinstall both gems multiple times.

**Comment by rjoberon** [comment]
Thank you. Fixed with the latest version.
